/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_matlice_stockfish_Stockfish */

#ifndef _Included_it_matlice_stockfish_Stockfish
#define _Included_it_matlice_stockfish_Stockfish
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_matlice_stockfish_Stockfish
 * Method:    nGetInstance
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_it_matlice_stockfish_Stockfish_nGetInstance
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     it_matlice_stockfish_Stockfish
 * Method:    nDestroyInstance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_it_matlice_stockfish_Stockfish_nDestroyInstance
  (JNIEnv *, jobject);

/*
 * Class:     it_matlice_stockfish_Stockfish
 * Method:    nSetOption
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_it_matlice_stockfish_Stockfish_nSetOption
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     it_matlice_stockfish_Stockfish
 * Method:    nSetPosition
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_it_matlice_stockfish_Stockfish_nSetPosition
  (JNIEnv *, jobject, jstring);

/*
 * Class:     it_matlice_stockfish_Stockfish
 * Method:    nMakeMove
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_it_matlice_stockfish_Stockfish_nMakeMove
  (JNIEnv *, jobject, jstring);

/*
 * Class:     it_matlice_stockfish_Stockfish
 * Method:    nSearchBestMove
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_it_matlice_stockfish_Stockfish_nSearchBestMove
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     it_matlice_stockfish_Stockfish
 * Method:    getFoundNextMove
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_it_matlice_stockfish_Stockfish_getFoundNextMove
  (JNIEnv *, jobject);

/*
 * Class:     it_matlice_stockfish_Stockfish
 * Method:    getFoundNextMoveStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_matlice_stockfish_Stockfish_getFoundNextMoveStr
  (JNIEnv *, jobject);

/*
 * Class:     it_matlice_stockfish_Stockfish
 * Method:    flip
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_it_matlice_stockfish_Stockfish_flip
  (JNIEnv *, jobject);

/*
 * Class:     it_matlice_stockfish_Stockfish
 * Method:    newGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_it_matlice_stockfish_Stockfish_nNewGame
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_it_matlice_stockfish_Stockfish_nDbgDisplay
        (JNIEnv *, jobject);

JNIEXPORT jfloat JNICALL Java_it_matlice_stockfish_Stockfish_nGetScore
        (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
