function(arch_amd64)
    set(ARCH x86_64 PARENT_SCOPE)
    set(BITS 64 PARENT_SCOPE)
    set(SSE YES PARENT_SCOPE)
    set(SSE2 YES PARENT_SCOPE)

    foreach (arg IN ITEMS ${ARGN})
        if (${arg} STREQUAL sse)
            set(SSE YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL popcnt)
            set(POPCNT YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL mmx)
            set(MMX YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL sse2)
            set(SSE2 YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL sses3)
            set(SSSE3 YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL sse)
            set(SSE YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL sse41)
            set(SSE YES PARENT_SCOPE)
            set(SSE2 YES PARENT_SCOPE)
            set(SSSE3 YES PARENT_SCOPE)
            set(SSE41 YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL modern)
            set(POPCNT YES PARENT_SCOPE)
            set(SSE YES PARENT_SCOPE)
            set(SSE2 YES PARENT_SCOPE)
            set(SSSE3 YES PARENT_SCOPE)
            set(SSE41 YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL avx2)
            set(POPCNT YES PARENT_SCOPE)
            set(SSE YES PARENT_SCOPE)
            set(SSE2 YES PARENT_SCOPE)
            set(SSSE3 YES PARENT_SCOPE)
            set(SSE41 YES PARENT_SCOPE)
            set(AVX2 YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL bmi2)
            set(POPCNT YES PARENT_SCOPE)
            set(SSE YES PARENT_SCOPE)
            set(SSE2 YES PARENT_SCOPE)
            set(SSSE3 YES PARENT_SCOPE)
            set(SSE41 YES PARENT_SCOPE)
            set(AVX2 YES PARENT_SCOPE)
            set(PEXT YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL avx512)
            set(POPCNT YES PARENT_SCOPE)
            set(SSE YES PARENT_SCOPE)
            set(SSE2 YES PARENT_SCOPE)
            set(SSSE3 YES PARENT_SCOPE)
            set(SSE41 YES PARENT_SCOPE)
            set(AVX2 YES PARENT_SCOPE)
            set(PEXT YES PARENT_SCOPE)
            set(AVX512 YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL vnni256)
            set(POPCNT YES PARENT_SCOPE)
            set(SSE YES PARENT_SCOPE)
            set(SSE2 YES PARENT_SCOPE)
            set(SSSE3 YES PARENT_SCOPE)
            set(SSE41 YES PARENT_SCOPE)
            set(AVX2 YES PARENT_SCOPE)
            set(PEXT YES PARENT_SCOPE)
            set(VNNI256 YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL vnni512)
            set(POPCNT YES PARENT_SCOPE)
            set(SSE YES PARENT_SCOPE)
            set(SSE2 YES PARENT_SCOPE)
            set(SSSE3 YES PARENT_SCOPE)
            set(SSE41 YES PARENT_SCOPE)
            set(AVX2 YES PARENT_SCOPE)
            set(PEXT YES PARENT_SCOPE)
            set(AVX512 YES PARENT_SCOPE)
            set(VNNI512 YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL avx2)
            set(POPCNT YES PARENT_SCOPE)
            set(SSE YES PARENT_SCOPE)
            set(SSE2 YES PARENT_SCOPE)
            set(SSSE3 YES PARENT_SCOPE)
            set(SSE41 YES PARENT_SCOPE)
            set(AVX2 YES PARENT_SCOPE)
        endif ()
        if (${arg} STREQUAL modern)
            set(POPCNT YES PARENT_SCOPE)
            set(SSE YES PARENT_SCOPE)
            set(SSE2 YES PARENT_SCOPE)
            set(SSSE3 YES PARENT_SCOPE)
            set(SSE41 YES PARENT_SCOPE)
        endif ()
    endforeach ()

    if (SSE STREQUAL YES)
        set(PREFETCH YES PARENT_SCOPE)
    endif ()
endfunction(arch_amd64)